"""Constants used through the library."""
GRAVITY = -9.80665  # m/s^2, ISO 80000-3
TRANSFORM_MATRIX_SHAPE = (4, 4)
TRANSFORM_VECTOR_LENGTH = 6
POSITION_VECTOR_LENGTH = TRANSFORM_VECTOR_LENGTH // 2
ROTATION_VECTOR_LENGTH = TRANSFORM_VECTOR_LENGTH // 2
